### ISSUE TITLE
Make primitive `Serialize`s implicit

### ISSUE THREAD

**Issue by guersam** [pocketberserker/scodec-msgpack#8]
There are some predefined `Serialize`s in its companion object. Making them implicit will help deriving complex ones, for example with Shapeless. WDYT?

**Comment by guersam** [comment]
An example: https://gist.github.com/guersam/5d62815ee51bfa805cff

**Comment by pocketberserker** [comment]
I respond 1ef3426 and c6b087b .
If you want to include your example, please send pull request.
